version: '3'

services:
  # rabbitmq:
  #   build:
  #     context: ../../RMQ
  #     dockerfile: Dockerfile
  #   ports:
  #     - '5672:5672'
  #     - '15672:15672'
  #   volumes:
  #     - ../../RMQ/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
  #     - ../../RMQ/data/:/var/lib/rabbitmq/
  #     - ../../RMQ/log/:/var/log/rabbitmq/
  user-service:
    build:
      context: ../../users-service
      dockerfile: dockerfile.dev
    volumes:
      - ../../users-service:/app
    ports:
      - '30001:3001'
    #depends_on:
    # - rabbitmq
  bustruck-service:
    build:
      context: ../../bustruck-service
      dockerfile: dockerfile.dev
    volumes:
      - ../../bustruck-service:/app
    ports:
      - '30002:3002'
    # depends_on:
    # - rabbitmq
